### ISSUE TITLE
Feature Suggestion: Docker (Container) Support.

### ISSUE THREAD

**Issue by 2IkHLHB** [PowerModder/Watchdog-Adult-Renamer#1]
Docker is continuing to become a popular option to run applications, softwares, and scripts.

Adding Docker support to Watchdog Adult Renamer would be an option that could increase the user base significantly, since most of us don't know how to run Python on our devices (in my case, a Synology NAS)

Thanks in advance for your time and for this project. Good day.

**Comment by PowerModder** [comment]
@2IkHLHB Hello! As i saw the documentation for how to make a python to docker is not something different from just running python to your system meaning that you still install dependecies to the container as i can understand. Anyway, I will try to make it but i don't have a experience on this.
you can btw take those files and install the requirements as i described and then i believe for Synology you can call it as python3

**Comment by 2IkHLHB** [comment]
Thank you for your reply.
The beauty of running containers inside Docker is that, for you the developer, putting the docket file together is almost identical to what you do right now. The difference is mainly for the end user, mainly because all we have to do is run a command like docker run (application name) and done. It's like running a small virtual machine just for your application, without the need for the end user to install anything else.
I appreciate the fact that you will try to make it happen, even with no docker experience.
In my case specifically with running all this on python, my NAS only has the option of running python 2 (2.7 I believe) I will give it another try this weekend.
Again, thank you so much for your time and your willingness to try the docker option. Good day.

**Comment by PowerModder** [comment]
@2IkHLHB  I try to install Docker Desktop at my system and get back an error and so far I can't resolve it. As I can see at some tutorials you need a Dockerfile and the .py files to make the container and then just call docker install and then docker run? I also I imagine that inside the docker i can have a python 3 instead of python 2.7? Anyway it's too confusing without being able to practice it at my system due to an error. The other thing that it's possible to avoid installing dependecies is to make an .exe file which already being done and tested and working fine. But again Synology can't run .exe AFAIK. 
You could have a Windows machine doing the downloads locally (local driver) and having the .exe running (watching and matching the scenes) and then after match it could move them to your NAS and in case of Unmatched content it could keep them locally. That way inside NAS you will have only matched and ready-to-plex scenes. BTW this is what i am doing.

**Comment by 2IkHLHB** [comment]
@PowerModder I totally appreciate you try to implement something you are not fully familiar with. Thank you for your time and everything. I'll see if I can make it work on my Synology by using Python. Again, thanks.
